### ISSUE TITLE
Investigate impact of upcoming change to API Gateway naming convention

### ISSUE THREAD

**Issue by jamesallardice** [orangejellyfish/serverless-starter#344]
In Serverless v3.0.0 the naming convention of API Gateway will switch from `${stage}-${service}` to `${service}-${stage}`. We should investigate this to determine if it will have any impact. If not, we can update the starter kit to opt-in to the new naming convention ahead of time as follows:

```yaml
provider:
  name: aws
  # ...

  apiGateway:
    shouldStartNameWithService: true
```
